# Render.com deployment configuration
# Place this file in your repository root as render.yaml

services:
  - type: web
    name: remote-mcp-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false  # Set this manually in Render dashboard
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /health